CREATE TABLE T_ROLE(
  id INT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  role_name   VARCHAR(60) NOT NULL COMMENT '角色名称',
  note VARCHAR(1024) COMMENT '备注',
  PRIMARY KEY (id)
);

SHOW TABLES ;

SELECT * FROM T_ROLE;

INSERT INTO T_ROLE VALUES (1,'admin','管理员');